### ISSUE TITLE
Visual studio 2017 support

### ISSUE THREAD

**Issue by lekararik** [tunnelvisionlabs/LangSvcV2#78] opened 2016-12-07 21:13 UTC
When are you planning to support visual studio 2017? I have the RC version and projects that rely on antlr tools don't compile.

**Comment by sharwell** [comment] 2016-12-07 22:00
Hi @lekararik,

I haven't yet updated the project to support Visual Studio 2017. However, the *build* support for ANTLR should not be relying on this at all, so that's very concerning. A couple questions:

1. Are you using ANTLR 3 or ANTLR 4?
2. Have you installed the ANTLR tools from NuGet? If so, can you list the packages (or link to the project if one is open source)?

**Comment by lekararik** [comment] 2016-12-07 22:28
@sharwell 
1. I am using Antlr4
2. I have no problem downloading from nuget/compiling projects that use Antlr4. I have problem compiling projects that use Antlr tools for visual studio

![image](https://cloud.githubusercontent.com/assets/15989650/20989331/f16d9d22-bcdc-11e6-8142-f7d308828523.png)
(Antlr language support)

Here is an error i get when i import such project (it buiilds on visual studio 2015 but doesn't build on visual studio 2017):

![image](https://cloud.githubusercontent.com/assets/15989650/20989379/20baebc0-bcdd-11e6-99d6-c6f77a55e92e.png)

**Comment by ben-may** [comment] 2017-01-11 19:45
@sharwell I also see this problem using the Antlr tools for visual studio.  And receive the same error as @lekararik
Any chance there is a bug-fix/patch coming for this soon?

**Comment by sharwell** [comment] 2017-01-11 19:47
It's on my list to install the RC tonight to start resolving a few issues in different extensions I participate in. I'll try to reproduce this as a high-priority item.

**Comment by ben-may** [comment] 2017-01-11 19:53
Thanks! appreciate it!

**Comment by ben-may** [comment] 2017-01-12 20:53
@sharwell debugging it seems that the 'HandleOutputDataReceived' callback registered to process.OutputDataReceived when running ikvm.exe is what ends up throwing the exception about Microsoft.Build.Framework.dll, if I comment out the OutputDataReceived and ErrorDataReceived registration, then everything runs ok (with the obvious exception that the GeneratedCodeFiles list doesn't get updated...

**Comment by sharwell** [comment] 2017-01-12 22:54
@lekararik @ben-may I was able to reproduce this today. It turns out the problem in part of the ANTLR C# target itself, which is a different project. I filed tunnelvisionlabs/antlr4cs#173 and am closing this one as **external**.

**Closed by sharwell** 2017-01-12 22:54 UTC
Labels: enhancement

**Comment by lekararik** [comment] 2017-01-13 12:47
@sharwell Thank you for your help!
