### ISSUE TITLE
No Antlr build action in .net standard or .net core projects

### ISSUE THREAD

**Issue by aspcompiler** [tunnelvisionlabs/LangSvcV2#99] opened 2018-08-15 21:27 UTC
I installed Antlr Language Support extension in Visual Studio 2017. When I .g4 grammar, there are no "Antlr" build action in .net core or .net standard projects. The 'Antlr' build action is only available in .net framework projects.

**Comment by aspcompiler** [comment] 2018-08-16 00:02
Additional information: I upgraded from 4.6.4 to Antlr4 4.6.5-beta002 and it worked in .net standard projects, but it is broken again in Antlr 4.6.5-rc002.

**Comment by sharwell** [comment] 2018-08-16 14:41
> I installed Antlr Language Support extension in Visual Studio 2017. When I .g4 grammar, there are no "Antlr" build action in .net core or .net standard projects.

This is a new feature being added to the 4.6.5 release(s).

> Additional information: I upgraded from 4.6.4 to Antlr4 4.6.5-beta002 and it worked in .net standard projects, but it is broken again in Antlr 4.6.5-rc002.

Duplicate of tunnelvisionlabs/antlr4cs#296, and a pesky problem for sure.

**Closed by sharwell** 2018-08-16 14:41 UTC
