### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by WizardOfMenlo** [tunnelvisionlabs/LangSvcV2#59] opened 2015-06-20 12:14 UTC
I've installed Visual Studio 2015 RC on a clean version of windows. I've then installed the Minecraft Mod pack and the java language support, however, whenever I create a console application (or any other by that matter) I get a message that : "Java file is not part of a workspace. Intellisense is not available". I've checked and the project compiles but the absence of Intellisense is quite annoying. Do I need to do anything to get it? Am I missing something?

**Comment by sharwell** [comment] 2015-06-20 20:33
Hi @WizardOfMenlo,

Thanks for taking the time to try out our extension and provide feedback. I'm sorry it's not working out like you hoped. :worried: 

Technically this issue belongs in the [tunnelvisionlabs/JavaForVS](https://github.com/tunnelvisionlabs/JavaForVS) repository since it has split from this one, but I'll go ahead and give you a quick overview.

Currently there is a very complicated/confusing relationship between the JavaForVS extension and the Minecraft Modding extension. You can read more about this in tunnelvisionlabs/JavaForVS#28. Your particular issue is caused by the fact that IntelliSense services are provided by the Minecraft extension, but only the Minecraft project templates contain the scripts necessary to enable this support. The other templates, including Console Application, weren't created with the Minecraft extension in mind, and the JavaForVS extension itself doesn't actually include any IntelliSense support.

I'm closing *this* issue since it's not the correct repository, but I encourage you to resubmit the issue to the JavaForVS repository. However, keep in mind that I don't currently have any timeline for implementing IntelliSense support within JavaForVS myself.

**Closed by sharwell** 2015-06-20 20:33 UTC

**Comment by WizardOfMenlo** [comment] 2015-06-21 10:22
Ok thank you very much for your time, I'll forward the issue to the other repo
